baseURL = "https://dp42.net/"
languageCode = "ja"
hasCJKLanguage = true
pygmentsCodefences = true
title = "Life, the Universe, and Technology"
theme = "final-frontier"

[params]
  author = "Koichi SATO"
  copyright = "Â© 2017-2019 Koichi SATO"
  twitter   = "https://twitter.com/_dp42"
  github    = "https://github.com/dp42/"

[permalinks]
   posts = "/posts/:year/:month/:slug/"

[outputFormats]
[outputFormats.RSS]
  basename = "feed"
